repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        files: ^server/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^server/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [pyproject-flake8]
        args: ["--config=server/pyproject.toml"]
        files: ^server/.*\.py$

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd api && npx eslint . --fix && cd ../discord && npx eslint . --fix'
        language: system
        files: \.(js|jsx|ts|tsx)$
        types: [file]

      - id: prettier
        name: prettier
        entry: bash -c 'cd api && npx prettier --write . && cd ../discord && npx prettier --write .'
        language: system
        files: \.(js|jsx|ts|tsx|json|css|md)$
        types: [file]
