services:
  server:
    build: ./server
    ports:
      - 8001:8001
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./server:/app
    depends_on:
      - postgres
      - ollama

  ollama:
    build: ./ollama
    ports:
      - 11434:11434
    volumes:
      - llmdata:/root/.ollama

  discord:
    build: ./discord
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API_GATEWAY_URL=http://server:8001
    volumes:
      - ./discord:/app
    depends_on:
      - server

  postgres:
    image: ankane/pgvector:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
  llmdata:
